/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hallseat;

import java.awt.event.KeyEvent;
import static java.lang.Class.forName;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
//import hallseat.ConnectionProvider;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.*;
import java.util.Vector;
import javax.swing.*;


/**
 *
 * @author Aristo_NPC
 */
public class room4 extends javax.swing.JFrame {

    Connection getCon=null;

    /**
     * Creates new form room1
     */
    public room4() {
        initComponents();
        getCon= ConnectionProvider.getCon();
        table_update();
        
    }
    
    PreparedStatement ps;
    ResultSet rs ;
    private void table_update()
    {
       
            int c;
            try {
               
                 ps = getCon.prepareStatement("SELECT * FROM `room4`");
                 ResultSet rs = (ResultSet) ps.executeQuery();
                 
                 ResultSetMetaData rsd = rs.getMetaData();
                 c = rsd.getColumnCount();
                 
                 DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
                 d.setRowCount(0);
                                 
                 while(rs.next())
                 {
                     Vector v2 = new Vector(); 
                     for(int i=1; i<=c; i++)
                     {
                        v2.add(rs.getString("sid"));
                         v2.add(rs.getString("sname"));
                         v2.add(rs.getString("dept"));
                         v2.add(rs.getString("batch"));
                         v2.add(rs.getString("bed"));
                         v2.add(rs.getString("status"));
                         
                        
                     }             
                     d.addRow(v2);
                     
                 }
        } catch (SQLException ex) {
            Logger.getLogger(ManageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtbatch = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtstatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtbed = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtdept = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("S.id:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 90, 40));
        getContentPane().add(txtbatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 91, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 100, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, 40));
        getContentPane().add(txtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 91, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("STATUS:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 114, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.name", "Dept", "S.id", "Batch", "Bed", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 480, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/room 104.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 314, 534));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Batch:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("BED:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 70, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("S.name:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setText("Dept:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 80, 40));
        getContentPane().add(txtbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 91, 40));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 91, 40));
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 91, 40));
        getContentPane().add(txtdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 91, 40));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 100, 40));

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new floor1().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String Sid = txtid.getText();
        String Sname = txtname.getText();
        String Dept = txtdept.getText();
        String Batch = txtbatch.getText();
        String BED = txtbed.getText();
        String STATUS = txtstatus.getText();
int test = Integer.parseInt(BED);
        if(test<1 || test>6){
        JOptionPane.showMessageDialog(null, "Please Enter a number between 1 to 6");
        }
        else{
      
        try {
           // Connection Con = ConnectionProvider.getCon();
            ps = getCon.prepareStatement("INSERT INTO `room4`(`sid`, `sname`, `dept`, `batch`, `bed`, `status`) VALUES (?,?,?,?,?,?)");
            ps.setString(1, Sid);
            ps.setString(2, Sname);
            ps.setString(3, Dept);
            ps.setString(4, Batch);
            ps.setString(5, BED);
            ps.setString(6, STATUS);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Insert");
           // tableDetails();
           table_update();
            txtid.setText("");
            txtname.setText("");
            txtdept.setText("");
            txtbatch.setText("");
            txtbed.setText("");
            txtstatus.setText("");            
            table_update();
           txtid.requestFocus();
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Already Booked");
        }}
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
     int selectedIndex=jTable1.getSelectedRow();
     
        txtid.setText(d.getValueAt(selectedIndex, 0).toString());
        txtname.setText(d.getValueAt(selectedIndex, 1).toString());
        txtdept.setText(d.getValueAt(selectedIndex, 2).toString());
        txtbatch.setText(d.getValueAt(selectedIndex, 3).toString());
        txtbed.setText(d.getValueAt(selectedIndex, 4).toString());
        txtstatus.setText(d.getValueAt(selectedIndex,5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String Sid = txtid.getText();
        String Sname = txtname.getText();
        String Dept = txtdept.getText();
        String Batch = txtbatch.getText();
        String BED = txtbed.getText();
        String STATUS = txtstatus.getText();
        
      
        try {
           // Connection Con = ConnectionProvider.getCon();
             ps = getCon.prepareStatement("UPDATE `room4` SET `sid`=?,`sname`=?,`dept`=?,`batch`=?,`bed`=?,`status`=? WHERE `sid`=?");
            ps.setString(1, Sid);
            ps.setString(2, Sname);
            ps.setString(3, Dept);
            ps.setString(4, Batch);
            ps.setString(5, BED);
            ps.setString(6, STATUS);
            ps.setString(7, Sid);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Update");
           // tableDetails();
           table_update();
            txtid.setText("");
            txtname.setText("");
            txtdept.setText("");
            txtbatch.setText("");
            txtbed.setText("");
            txtstatus.setText("");
             
      
            table_update();
           txtid.requestFocus();
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel d = (DefaultTableModel)jTable1.getModel();
     int selectedIndex=jTable1.getSelectedRow();
     
     String Sid = txtid.getText();
        String Sname = txtname.getText();
        String Dept = txtdept.getText();
        String Batch = txtbatch.getText();
        String BED = txtbed.getText();
        String STATUS = txtstatus.getText();
       
        
        try {
           // Connection Con = ConnectionProvider.getCon();
             ps = getCon.prepareStatement("DELETE FROM `room4` WHERE `sid`=?");
             ps.setString(1, Sid);
           
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Delete");
           // tableDetails();
           table_update();
//            
//      
            table_update();
            txtname.requestFocus();
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(room4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(room4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(room4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(room4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new room4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbatch;
    private javax.swing.JTextField txtbed;
    private javax.swing.JTextField txtdept;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtstatus;
    // End of variables declaration//GEN-END:variables
}
